version: '3.9'
services:
  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    env_file:
      - .env
    ports:
      - "3000:3000"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  redis_data: 